### ISSUE TITLE
ERC-20 based gas model

### ISSUE THREAD

**Issue by shogochiai** [cryptoeconomicslab/PlasmaVM-JS#14]
- Configurable Gas payable token
- UTXO based gas payment design
- Gas station API

**Comment by shogochiai** [comment]
You mean, without Gas?

**Comment by syuhei176** [comment]
Yes, Let's list the reasons why gas.

- to avoid large amount of transaction
- to avoid heavy transaction

**Comment by shogochiai** [comment]
No
- Avoid DDoS
- Avod Infinite Loop

**Comment by syuhei176** [comment]
> Avoid Infinite Loop
 constant runLimit can avoid this.

 or hoe about distributing hidden gas to all user at first?

**Comment by shogochiai** [comment]
Operator defined runLimit: 

1. Okay but wanna make sure it works well near the upper bound of runLimit

2. How about this: Almost all usual Tx doesn't need to pay Gas but the Tx beyond runLimit or rateLimit... must pay expensive Gas as penalty

**Comment by shogochiai** [comment]
I got this (https://github.com/cryptoeconomicslab/PlasmaVM-JS/issues/14#issuecomment-420840238) is kinda timeout for usual web app. More like "time"out is not appropriately reflecting TxVM computational resource usage, so that "gas"out is better. LGTM
